const assert = require('node:assert/strict');
const sqlite3 = require('sqlite3');
const { createLifecycle, sql, renderTemplate, validateTemplate, normalizeOrderStatus, ORDER_STATUSES, hanjinTrackingUrl } = require('../internal/order-lifecycle.cjs');
const { createOrderService } = require('../internal/order-service.cjs');
const { randomUUID } = require('node:crypto');
(async () => {
  assert.deepEqual(ORDER_STATUSES, ['주문접수-택배', '주문접수-픽업(계좌이체)', '주문접수-픽업(현장결제)', '입금확인-택배', '입금확인-픽업', '택배발송', '주문취소']);
  assert.equal(normalizeOrderStatus('주문', { address: '[직접 픽업]', memo: '현장결제' }), '주문접수-픽업(현장결제)');
  assert.equal(normalizeOrderStatus('결제', { address: '택배 배송지' }), '입금확인-택배');
  const db = new sqlite3.Database(':memory:'); const q = sql(db);
  await q.run("CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, phone TEXT, address TEXT, memo TEXT, items TEXT, total_price INTEGER, status TEXT DEFAULT '주문', tracking_number TEXT, courier TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)");
  const lifecycle = createLifecycle(db);
  const service = createOrderService(db, { lifecycle });
  const payload = { name: '가상주문', phone: '01000000000', address: '[직접 픽업] 날짜: 2026-09-15 / 시간: 14:00', memo: '현장결제', items: [{ name: '가상상품', quantity: 1, unit: '개' }], totalPrice: 1000, requestKey: randomUUID() };
  const receipts = await Promise.all(Array.from({ length: 5 }, () => service.submit(payload)));
  const id = receipts[0].orderId;
  assert.equal(new Set(receipts.map(r => r.orderId)).size, 1);
  assert.equal((await lifecycle.history(id)).events.length, 1);
  assert.equal((await lifecycle.history(id)).legacy, false);
  assert.equal((await q.get('SELECT count(*) AS n FROM order_event_notifications')).n, 1);
  assert.equal((await q.get('SELECT count(*) AS n FROM order_notifications')).n, 0);
  assert.equal((await q.get('SELECT status FROM orders WHERE id = ?', [id])).status, '주문접수-픽업(현장결제)');
  await assert.rejects(lifecycle.update(id, { status: '택배발송', courier: '한진택배', tracking_number: '123' }, 0, '주문 목록'), /직접 픽업/);
  await assert.rejects(lifecycle.update(id, { status: '입금확인-픽업' }, 0, '주문 목록'), /현장결제/);
  await lifecycle.update(id, { status: '주문취소' }, 0, '주문 목록');
  assert.equal((await lifecycle.update(id, { status: '주문취소' }, 1, '주문 목록')).unchanged, true);
  assert.equal((await lifecycle.history(id)).events.length, 2);
  await assert.rejects(lifecycle.update(id, { status: '주문접수-픽업(현장결제)' }, 0, '주문 목록'), { status: 409 });
  const simultaneous = await Promise.allSettled([lifecycle.update(id, { status: '주문접수-픽업(현장결제)' }, 1, '주문 상세'), lifecycle.update(id, { status: '주문취소' }, 1, '주문 목록')]);
  assert.equal(simultaneous.filter(r => r.status === 'fulfilled').length, 1);
  const legacy = await q.run("INSERT INTO orders (name, phone, address, memo, items, total_price) VALUES ('가상 택배', '01000000000', '가상 배송지', '', '[]', 1000)");
  const orderId = legacy.id;
  assert.equal((await lifecycle.history(orderId)).legacy, true);
  await assert.rejects(lifecycle.update(orderId, { status: '택배발송' }, 0, '주문 상세'), /택배사와 운송장/);
  const template = (await lifecycle.templates()).templates.find(t => t.status === '택배발송');
  await lifecycle.saveTemplate('택배발송', { ...template, enabled: true, provider_code: 'FAKE-ONLY' });
  await assert.rejects(lifecycle.saveTemplate('택배발송', template), { status: 409 });
  await lifecycle.update(orderId, { status: '택배발송', tracking_number: '001234', courier: '한진택배' }, 0, '주문 목록');
  assert.equal((await lifecycle.history(orderId)).events.length, 1);
  let notifications = await q.all('SELECT * FROM order_event_notifications WHERE order_id = ?', [orderId]);
  assert.equal(notifications.length, 1);
  assert.equal(JSON.parse(notifications[0].rendered_json).button_url, hanjinTrackingUrl('001234'));
  assert.equal(notifications[0].status, 'disabled');
  await lifecycle.update(orderId, { tracking_number: '999999', courier: '한진' }, 1, '주문 상세');
  notifications = await q.all('SELECT * FROM order_event_notifications WHERE order_id = ?', [orderId]);
  assert.equal(notifications.length, 2);
  assert.ok(notifications.some(n => JSON.parse(n.rendered_json).button_url === hanjinTrackingUrl('999999')));
  await lifecycle.update(orderId, { status: '주문취소' }, 2, '주문 목록');
  assert.equal((await q.get('SELECT * FROM orders WHERE id = ?', [orderId])).tracking_number, '999999');
  await lifecycle.update(orderId, { status: '입금확인-택배' }, 3, '주문 목록');
  assert.equal((await q.get('SELECT * FROM orders WHERE id = ?', [orderId])).courier, '한진');
  const fixture = { name: '가상', id: 1, total_price: 100, created_at: '2026-09-13 01:30:00', address: payload.address, tracking_number: '000', courier: '한진택배' };
  assert.equal(renderTemplate({ body: '#{픽업일시}' }, fixture).body, '2026-09-15 14:00');
  assert.equal(renderTemplate({ body: '#{수령인}' }, fixture).body, '가상');
  assert.equal(renderTemplate({ button_url: '#{배송조회링크}' }, fixture).button_url, 'https://www.hanjin.com/kor/CMS/DeliveryMgr/WaybillResult.do?mCode=MN038&wblnum=000&schLang=KR&wblnumText=');
  assert.ok(renderTemplate({ body: '#{픽업일시}' }, { ...fixture, address: '가상 배송지' }).errors.length);
  assert.ok(renderTemplate({ button_url: '#{배송조회링크}' }, { ...fixture, courier: '다른택배' }).errors.length);
  assert.throws(() => validateTemplate({ body: '#{없는변수}' }), /변수/);
  assert.throws(() => validateTemplate({ body: '#{주문자명' }), /변수/);
  assert.throws(() => validateTemplate({ body: '안내', button_label: '조회', button_url: 'javascript:alert(1)' }), /https/);
  const count = (await lifecycle.history(orderId)).events.length;
  const originalRun = db.run.bind(db);
  db.run = function(query, params, callback) {
    if (query.startsWith('INSERT INTO order_event_notifications')) { callback(new Error('SIMULATED_WRITE_FAILURE')); return this; }
    return originalRun(query, params, callback);
  };
  await assert.rejects(lifecycle.update(orderId, { status: '주문취소' }, 4, '주문 상세'), /SIMULATED/);
  assert.equal((await q.get('SELECT * FROM orders WHERE id = ?', [orderId])).status, '입금확인-택배');
  assert.equal((await lifecycle.history(orderId)).events.length, count);
  await assert.rejects(service.submit({ ...payload, requestKey: randomUUID() }), /SIMULATED/);
  assert.equal((await q.get('SELECT count(*) AS n FROM orders')).n, 2);
  db.run = originalRun;
  await new Promise(resolve => db.close(resolve));
  const migrationDb = new sqlite3.Database(':memory:'); const migration = sql(migrationDb);
  await migration.run("CREATE TABLE orders (id INTEGER PRIMARY KEY, address TEXT, memo TEXT, status TEXT, revision INTEGER NOT NULL DEFAULT 0)");
  await migration.run('CREATE TABLE notification_templates (status TEXT PRIMARY KEY, body TEXT NOT NULL, provider_code TEXT NOT NULL, button_label TEXT NOT NULL, button_url TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1)');
  await migration.run("INSERT INTO notification_templates (status, body, provider_code, button_label, button_url, enabled, version) VALUES ('주문', '기존 주문 문구', 'APPROVED-ORDER', '', '', 1, 3), ('결제', '기존 입금 문구', 'APPROVED-PAY', '', '', 1, 2), ('택배사', '#{운송장번호}', 'APPROVED-SHIP', '배송조회', '#{배송조회링크}', 1, 4), ('주문취소', '기존 취소 문구', 'APPROVED-CANCEL', '', '', 0, 5)");
  await migration.run("INSERT INTO orders (id, address, memo, status) VALUES (1, '택배 배송지', '', '주문'), (2, '[직접 픽업]', '계좌이체', '주문'), (3, '[직접 픽업]', '현장결제', '주문'), (4, '택배 배송지', '', '결제'), (5, '[직접 픽업]', '', '결제'), (6, '택배 배송지', '', '택배사')");
  const migratedLifecycle = createLifecycle(migrationDb); await migratedLifecycle.ensureSchema();
  assert.deepEqual((await migration.all('SELECT status FROM orders ORDER BY id')).map(row => row.status), ['주문접수-택배', '주문접수-픽업(계좌이체)', '주문접수-픽업(현장결제)', '입금확인-택배', '입금확인-픽업', '택배발송']);
  const migratedTemplates = (await migratedLifecycle.templates()).templates;
  assert.equal(migratedTemplates.length, 7);
  assert.equal(migratedTemplates.find(row => row.status === '주문접수-픽업(현장결제)').provider_code, 'APPROVED-ORDER');
  assert.equal(migratedTemplates.find(row => row.status === '입금확인-픽업').body, '기존 입금 문구');
  assert.equal(migratedTemplates.find(row => row.status === '택배발송').button_url, '#{배송조회링크}');
  assert.equal((await migration.get("SELECT count(*) AS n FROM notification_templates WHERE status IN ('주문', '결제', '택배사')")).n, 0);
  await new Promise(resolve => migrationDb.close(resolve));
  console.log('PASS: atomic history + notification preparation, duplicate requests, concurrent updates, rollback, tracking resends, shipping preservation, template versions, variables and pickup. No external calls.');
})().catch(error => { console.error(error); process.exitCode = 1; });
