const assert = require('node:assert/strict');
const sqlite3 = require('sqlite3');
const { createLifecycle, sql, renderTemplate, validateTemplate, HANJIN } = require('../internal/order-lifecycle.cjs');
const { createOrderService } = require('../internal/order-service.cjs');
const { randomUUID } = require('node:crypto');
(async () => {
  const db = new sqlite3.Database(':memory:'); const q = sql(db);
  await q.run("CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, phone TEXT, address TEXT, memo TEXT, items TEXT, total_price INTEGER, status TEXT DEFAULT '주문', tracking_number TEXT, courier TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)");
  const lifecycle = createLifecycle(db);
  const service = createOrderService(db, { lifecycle });
  const payload = { name: '가상주문', phone: '01000000000', address: '[직접 픽업] 날짜: 2026-09-15 / 시간: 14:00', memo: '현장결제', items: [{ name: '가상상품', quantity: 1, unit: '개' }], totalPrice: 1000, requestKey: randomUUID() };
  const receipts = await Promise.all(Array.from({ length: 5 }, () => service.submit(payload)));
  const id = receipts[0].orderId;
  assert.equal(new Set(receipts.map(r => r.orderId)).size, 1);
  assert.equal((await lifecycle.history(id)).events.length, 1);
  assert.equal((await lifecycle.history(id)).legacy, false);
  assert.equal((await q.get('SELECT count(*) AS n FROM order_event_notifications')).n, 1);
  assert.equal((await q.get('SELECT count(*) AS n FROM order_notifications')).n, 0);
  await assert.rejects(lifecycle.update(id, { status: '택배사', courier: '한진택배', tracking_number: '123' }, 0, '주문 목록'), /직접 픽업/);
  await lifecycle.update(id, { status: '결제' }, 0, '주문 목록');
  assert.equal((await lifecycle.update(id, { status: '결제' }, 1, '주문 목록')).unchanged, true);
  assert.equal((await lifecycle.history(id)).events.length, 2);
  await assert.rejects(lifecycle.update(id, { status: '주문취소' }, 0, '주문 목록'), { status: 409 });
  const simultaneous = await Promise.allSettled([lifecycle.update(id, { status: '주문취소' }, 1, '주문 상세'), lifecycle.update(id, { status: '주문' }, 1, '주문 목록')]);
  assert.equal(simultaneous.filter(r => r.status === 'fulfilled').length, 1);
  const legacy = await q.run("INSERT INTO orders (name, phone, address, memo, items, total_price) VALUES ('가상 택배', '01000000000', '가상 배송지', '', '[]', 1000)");
  const orderId = legacy.id;
  assert.equal((await lifecycle.history(orderId)).legacy, true);
  await assert.rejects(lifecycle.update(orderId, { status: '택배사' }, 0, '주문 상세'), /택배사와 운송장/);
  const template = (await lifecycle.templates()).templates.find(t => t.status === '택배사');
  await lifecycle.saveTemplate('택배사', { ...template, enabled: true, provider_code: 'FAKE-ONLY' });
  await assert.rejects(lifecycle.saveTemplate('택배사', template), { status: 409 });
  await lifecycle.update(orderId, { status: '택배사', tracking_number: '001234', courier: '한진택배' }, 0, '주문 목록');
  assert.equal((await lifecycle.history(orderId)).events.length, 1);
  let notifications = await q.all('SELECT * FROM order_event_notifications WHERE order_id = ?', [orderId]);
  assert.equal(notifications.length, 1);
  assert.equal(JSON.parse(notifications[0].rendered_json).button_url, HANJIN + '001234');
  assert.equal(notifications[0].status, 'disabled');
  await lifecycle.update(orderId, { tracking_number: '999999', courier: '한진' }, 1, '주문 상세');
  notifications = await q.all('SELECT * FROM order_event_notifications WHERE order_id = ?', [orderId]);
  assert.equal(notifications.length, 2);
  assert.ok(notifications.some(n => JSON.parse(n.rendered_json).button_url === HANJIN + '999999'));
  await lifecycle.update(orderId, { status: '주문취소' }, 2, '주문 목록');
  assert.equal((await q.get('SELECT * FROM orders WHERE id = ?', [orderId])).tracking_number, '999999');
  await lifecycle.update(orderId, { status: '결제' }, 3, '주문 목록');
  assert.equal((await q.get('SELECT * FROM orders WHERE id = ?', [orderId])).courier, '한진');
  const fixture = { name: '가상', id: 1, total_price: 100, created_at: '2026-09-13 01:30:00', address: payload.address, tracking_number: '000', courier: '한진택배' };
  assert.equal(renderTemplate({ body: '#{픽업일시}' }, fixture).body, '2026-09-15 14:00');
  assert.ok(renderTemplate({ body: '#{픽업일시}' }, { ...fixture, address: '가상 배송지' }).errors.length);
  assert.ok(renderTemplate({ button_url: '#{배송조회링크}' }, { ...fixture, courier: '다른택배' }).errors.length);
  assert.throws(() => validateTemplate({ body: '#{없는변수}' }), /변수/);
  assert.throws(() => validateTemplate({ body: '#{주문자명' }), /변수/);
  assert.throws(() => validateTemplate({ body: '안내', button_label: '조회', button_url: 'javascript:alert(1)' }), /https/);
  const count = (await lifecycle.history(orderId)).events.length;
  const originalRun = db.run.bind(db);
  db.run = function(query, params, callback) {
    if (query.startsWith('INSERT INTO order_event_notifications')) { callback(new Error('SIMULATED_WRITE_FAILURE')); return this; }
    return originalRun(query, params, callback);
  };
  await assert.rejects(lifecycle.update(orderId, { status: '주문취소' }, 4, '주문 상세'), /SIMULATED/);
  assert.equal((await q.get('SELECT * FROM orders WHERE id = ?', [orderId])).status, '결제');
  assert.equal((await lifecycle.history(orderId)).events.length, count);
  await assert.rejects(service.submit({ ...payload, requestKey: randomUUID() }), /SIMULATED/);
  assert.equal((await q.get('SELECT count(*) AS n FROM orders')).n, 2);
  db.run = originalRun;
  await new Promise(resolve => db.close(resolve));
  console.log('PASS: atomic history + notification preparation, duplicate requests, concurrent updates, rollback, tracking resends, shipping preservation, template versions, variables and pickup. No external calls.');
})().catch(error => { console.error(error); process.exitCode = 1; });
