const assert = require('node:assert/strict');
const {targets,orderRow,build}=require('../shipping-export.js');
const order={id:1,name:'가상고객',phone:'01000000000',address:'[01234] 가상로 12',memo:'문 앞',items:[{name:'특품 오이',quantity:5,unit:'kg'},{name:'상품 오이',quantity:10,unit:'개'}]};
const before=JSON.stringify(order), row=orderRow(order);
assert.deepEqual(row,['가상고객','01000000000','','01000000000','01234','가상로 12',1,'특품 오이 5kg, 상품 오이 10개','c','선불','','문 앞']);
for(const [qty,code] of [[9.5,'c'],[10,'d'],[12,'d']]) assert.equal(orderRow({...order,items:[{name:'오이',quantity:qty,unit:'kg'}]})[8],code);
assert.equal(orderRow({...order,items:[{name:'오이',quantity:60,unit:'개'}]})[8],'d');
assert.equal(orderRow({...order,basicAddress:'가상로 12',detailAddress:undefined,postcode:'00123'})[5],'가상로 12');
assert.equal(orderRow({...order,basicAddress:'가상로 12',detailAddress:'  101호  '})[5],'가상로 12 101호');
assert.equal(orderRow({...order,address:'[01234] 가상로 12 null undefined'})[5],'가상로 12');
const pickup={...order,id:2,address:'[직접 픽업]'}, other={...order,id:3};
assert.deepEqual(targets([order,pickup,other],[other],[]),[other]);
assert.deepEqual(targets([order,pickup,other],[other],['1','2']),[order]);
assert.deepEqual(targets([order,pickup],[order],['2']),[]);
assert.equal(JSON.stringify(order),before);
assert.equal(Buffer.from(build([order])).readUInt32LE(),0x04034b50);
assert.throws(()=>orderRow({...order,items:[{quantity:NaN,unit:'kg'}]}));
if(process.argv[2]) require('node:fs').writeFileSync(process.argv[2],build([order,{...order,id:3,name:'가상고객2',items:[{name:'한글 복수 상품',quantity:10,unit:'kg'}]}]));
console.log('PASS: shipping fields, text zeros, 10kg boundary, count weight, optional address, selected/filtered/pickup exclusion, no mutation, ZIP generation. Synthetic data only.');
